### ISSUE TITLE
TODOリスト

### ISSUE THREAD

**Issue by ayame113** [ayame113/shinshu-hackathon#3]
- [x] 背景の色を変更する
- [x] フキダシの形を変更する

**Comment by Cyndaquil1999** [comment]
- [x] 入力欄のサイズを調整する（右側が少しでかい気がする...。）
- [x] 新しい問題を生成した際に、履歴を削除する
- [x] 降参ボタンの追加

**Comment by Cyndaquil1999** [comment]
- 新しい問題を生成した際に、履歴を削除する
- 降参ボタンの追加

**Comment by ayame113** [comment]
- [x] 出典を明示する
